---
manifest: manifest.txt
masked_ref: /net/eichler/vol5/home/bnelsj/projects/rd_custom_contig/mask/CH17_1-6261457/fastas/CH17_1-6261457.rp.trf.mask.fasta
contigs: /net/eichler/vol5/home/bnelsj/projects/rd_custom_contig/CH17_1-6261457_lengths.tab
window_size: 5000000
use_source_contigs_for_array: False
array_contigs: 
        - CH17_1-6261457
jobfile: "mapping_joblist.json"
