---
reference: hg19
manifest: manifest.txt

hg19:
    masked_ref: /net/eichler/vol2/eee_shared/assemblies/hg19/indexes/mrsfastULTRA/hg19_masked
    contigs: /net/eichler/vol7/home/psudmant/genomes/contigs/hg19_contigs.txt
hg38:
    masked_ref: /net/eichler/vol2/eee_shared/assemblies/hg38/indexes/mrsfastULTRA/hg38.rmsk_and_trf.fa
    contigs: /net/eichler/vol2/eee_shared/assemblies/hg38/indexes/mrsfast_hg38/hg38_contigs.tab
custom_contig:
    masked_ref: /net/eichler/vol23/projects/human_diversity/nobackups/bnelsj/hsdg/FAM115C/rd_custom_contig_hgdp/mask/fastas/FAM115C_LOC154761_final/FAM115C_LOC154761_final.rp.trf.mask.fasta
    contigs: /net/eichler/vol23/projects/human_diversity/nobackups/bnelsj/hsdg/FAM115C/rd_custom_contig_hgdp/FAM115C_LOC154761_final_lengths.tab

bam_partitions: 500

array_contigs: 
        - FAM115C_LOC154761_final

# If this is set to True, the read counter will automatically assign contigs to numpy or lil arrays and rebalance every 1 million reads
auto_assign: True
max_basepairs_in_mem: 300000000

